Support for React Native 0.60+
wnr/react-native-picker-input pull request #1
Opened 2020-01-05 18:52 UTC by wintererik

### Summary
React Native 0.60 introduced autolinking of modules.
This pull request aims to support this together with fixing other warnings related to using RN 0.60+.

### Changelog
- Refactoring on files to simplify autolinking
- Fix warnings/errors from podspec validation when running pod install. At the same time reading data from package.json
- Updates on Readme describing autolinking
- Migrating from use of componentWillReceiveProps which is deprecated as of React 16.3.

2020-01-07 10:27 UTC, wnr requested changes
Hej! Så roligt med en PR till detta projekt :)

Jag har kommenterat på ett ställe som du gärna får titta på. 

Jag undrar även ifall ni testat ordentligt att det inte "laggar" eller blir någon konstig visuell bugg när man ändrar props, eftersom uppdateringen nu sker efter rendering (didUpdate) istället för före (willReceiveProps)?

2020-01-07 10:27 UTC, wnr commented on picker-input-ios.js
>              pickerInputHandler.componentWillReceiveProps(ReactNative.findNodeHandle(this.refs.input), {
Borde även `pickerInputHandler.componentWillReceiveProps` ändras till `pickerInputHandler. componentDidUpdate`?

2020-01-07 18:23 UTC, wintererik commented on picker-input-ios.js
>              pickerInputHandler.componentWillReceiveProps(ReactNative.findNodeHandle(this.refs.input), {
> Hej! Så roligt med en PR till detta projekt :)
:)

> Jag undrar även ifall ni testat ordentligt att det inte "laggar" eller blir någon konstig visuell bugg när man ändrar props, eftersom uppdateringen nu sker efter rendering (didUpdate) istället för före (willReceiveProps)?
Ja, det såg ok ut.

> Borde även `pickerInputHandler.componentWillReceiveProps` ändras till `pickerInputHandler. componentDidUpdate`?
Ja, helt klart! Pushat ändring nu.

2020-01-08 10:24 UTC, wnr approved these changes

2020-01-08 10:25 UTC, wnr commented on picker-input-ios.js
>              pickerInputHandler.componentWillReceiveProps(ReactNative.findNodeHandle(this.refs.input), {
Tackar, ser bra ut! Jag mergar.

2020-01-08 10:25 UTC, merged